spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      host: desdora
      port: 27017
      username: citizix
      password: S3cret
      database: reactive-boot
      authentication-database: admin
  jackson:
    default-property-inclusion: non_null
